source(file.path("..","..","R","pvr.R"))
source(file.path("..","..","R","p15_pv_first_pass.R"))
testthat::test_that("term exclusions distinguish missing, zero and bullet-like terms", {
  testthat::expect_equal(p15_term_reason(0,10,0),"usable_stylized_terms")
  testthat::expect_equal(p15_term_reason(NA,10,0),"missing_term_field")
  testthat::expect_equal(p15_term_reason(2,0,0),"nonpositive_maturity")
  testthat::expect_equal(p15_term_reason(2,10,10),"bullet_like_pair_not_equal_principal_baseline")
  testthat::expect_equal(p15_term_reason(2,10,12),"grace_exceeds_maturity")
})
testthat::test_that("PV respects cash-flow identity and actual fractional payment time", {
  f <- p15_pv_schedule(5,10,2)
  testthat::expect_equal(p15_stream_pv(f,5),100,tolerance=1e-10)
  testthat::expect_equal(p15_stream_pv(f,0),sum(f$debt_service))
  f <- p15_pv_schedule(0,2.5,.5)
  testthat::expect_equal(f$principal,c(25,50,25))
  testthat::expect_equal(f$payment_time_years,c(1,2,2.5))
  testthat::expect_equal(p15_stream_pv(f,10),25/1.1+50/1.1^2+25/1.1^2.5)
  testthat::expect_gt(p15_stream_pv(f,10),present_value(f,10))
  testthat::expect_error(p15_stream_pv(f,-100))
  testthat::expect_error(p15_pv_schedule(2,10,12))
})
