source(file.path("..","..","R","pvr.R"))
source(file.path("..","..","R","p15_pv_first_pass.R"))
source(file.path("..","..","R","p15_bullet_extension.R"))
testthat::test_that("exact positive equality is required and zero coupon is valid",{
  testthat::expect_error(p15_bullet_equal_schedule(2,10,12))
  testthat::expect_error(p15_bullet_equal_schedule(2,10,9.99999))
  testthat::expect_error(p15_bullet_equal_schedule(-1,10,10))
  testthat::expect_error(p15_bullet_equal_schedule(NA_real_,10,10))
  testthat::expect_error(p15_bullet_equal_schedule(2,0,0))
  testthat::expect_error(p15_bullet_equal_schedule(c(1,2),10,10))
  f <- p15_bullet_equal_schedule(0,10,10)
  testthat::expect_equal(sum(f$interest),0)
  testthat::expect_equal(p15_stream_pv(f,5),100/1.05^10)
})
testthat::test_that("principal is final-only and independent PV matches",{
  f <- p15_bullet_equal_schedule(5,10,10)
  testthat::expect_equal(f$principal,c(rep(0,9),100))
  testthat::expect_equal(p15_stream_pv(f,5),100,tolerance=1e-10)
  f <- p15_bullet_equal_schedule(4,2.5,2.5)
  testthat::expect_equal(f$payment_time_years,c(1,2,2.5))
  testthat::expect_equal(f$interest,c(4,4,2))
  testthat::expect_equal(f$principal,c(0,0,100))
  testthat::expect_equal(p15_stream_pv(f,7),4/1.07+4/1.07^2+102/1.07^2.5)
  testthat::expect_equal(p15_stream_pv(f,7),p15_bullet_independent_pv(4,2.5,7))
  testthat::expect_equal(p15_stream_pv(f,0),110)
  testthat::expect_gt(p15_stream_pv(f,7),p15_stream_pv(f,8))
  # A fractional first/final period below one year must also work.
  f <- p15_bullet_equal_schedule(4,.5,.5)
  testthat::expect_equal(p15_stream_pv(f,7),102/1.07^.5)
})
