source(file.path("..","..","R","pvr.R"))
source(file.path("..","..","R","p15_pv_first_pass.R"))
source(file.path("..","..","R","p15_bullet_extension.R"))
source(file.path("..","..","R","p15_pv_interpretation.R"))
testthat::test_that("order-averaged decomposition is exact and directional",{
  a <- p15_analysis_schedule(2,20,5); b <- p15_analysis_schedule(4,10,2)
  d <- p15_pv_two_block(a,b,5,9)
  testthat::expect_equal(d[["change"]],d[["benchmark_effect"]]+d[["terms_effect"]],tolerance=1e-10)
  testthat::expect_lt(d[["benchmark_effect"]],0)
  r <- p15_pv_two_block(b,a,9,5)
  testthat::expect_equal(d,-r,tolerance=1e-10)
  testthat::expect_equal(p15_pv_two_block(a,a,5,9)[["terms_effect"]],0)
  testthat::expect_equal(p15_pv_two_block(a,b,5,5)[["benchmark_effect"]],0)
  testthat::expect_equal(p15_pv_two_block(a,a,5,5)[["change"]],0)
  f <- p15_analysis_schedule(2,10,10)
  testthat::expect_equal(sum(f$principal),100)
})
